name: ritmora
description: "Reproductor multiplataforma de música de YouTube Music sin necesidad de suscripción ni inicio de sesión."
publish_to: "none"
version: 0.1.8

environment:
  sdk: ^3.5.4
  flutter: "3.29.0"

dependencies:
  animate_do: ^3.3.4
  audio_session: ^0.1.23
  audioplayers: ^6.1.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  csv: ^6.0.0
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_distributor: ^0.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.14
  loading_indicator: ^3.1.1
  marquee: ^2.3.0
  palette_generator: ^0.3.3+5
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  rename: ^3.1.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: ^0.5.28
  synchronized: ^3.3.0+3
  uuid: ^4.5.1
  youtube_explode_dart: ^2.3.6

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/

  # Fonts
  fonts:
    - family: Titulo
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
